import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Montserrat } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "bootstrap/dist/css/bootstrap.min.css";

import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
        </head>
        <body className={montserrat.className}>
          <Navbar />
          <ToastContainer />
          {children}
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pzjw8y+HDl9Tn6PqpgB1D46NEHv1zg3FZhFgIF1OJyo2yyw9b4f+1z3WxS9bZxS"
            crossOrigin="anonymous"
          ></script>
        </body>
      </html>
    </ClerkProvider>
  );
}
